FROM python:3.12.11-slim

WORKDIR /app
COPY /requirements.txt /app/requirements.txt
COPY /DataFrame_general_overview.py /app/DataFrame_general_overview.py
COPY pages/ pages/

RUN pip install -r requirements.txt
EXPOSE 8501
HEALTHCHECK CMD curl --fail http://localhost:8501/_stcore/health

ENTRYPOINT ["streamlit", "run", "DataFrame_general_overview.py", "--server.port=8501", "--server.address=0.0.0.0"]